version: '3'
services:
  crawler-news:
    container_name: 'crawler-news'
    restart: always
    build: .
    image: 'germey/crawler-news'
    command: 'python3 run.py'
    environment:
      PGSQL_HOST:
      PGSQL_PORT:
      PGSQL_USER:
      PGSQL_PASSWORD: